const form = document.getElementById("myForm");
const display = document.getElementById("displayItem");
const easyRadio = document.getElementById("easyDif");
const intermediateRadio = document.getElementById("intermediateDif");
const hardRadio = document.getElementById("hardDif");
const extremeRadio = document.getElementById("extremeDif");

const easyList = [
  "To-do list application",
  "Weather forecast website",
  "Recipe sharing website",
  "Personal blog platform",
  "Online calculator tool",
  "Quote of the day website",
  "Online countdown timer",
  "Random joke generator website",
  "Simple chat application",
  "BMI calculator website",
  "Currency converter tool",
  "Word counter tool",
  "Random password generator website",
  "Note-taking application",
  "Online quiz platform",
  "Simple e-commerce website for one product",
  "Event countdown website",
  "Tic-tac-toe game website",
  "Basic contact form website",
  "Daily horoscope website",
  "Simple blog CMS",
  "Trivia quiz website",
  "Color palette generator tool",
  "Random fact generator website",
  "Basic calculator tool",
  "Text-to-speech converter website",
  "Basic survey form website",
  "Tip calculator tool",
  "Basic URL shortener website",
  "Quote generator website",
  "Simple blog with commenting feature",
  "Fibonacci sequence generator website",
  "Basic voting/polling website",
  "Basic image slideshow website",
  "Basic calendar application",
  "Basic countdown timer website",
  "Simple weather forecast website",
  "Basic portfolio website",
  "Random number generator website",
  "Basic chat room application",
  "Simple task manager application",
  "Simple note-sharing website",
  "Basic news aggregator website",
  "Simple calculator tool",
  "Basic blog with tagging feature",
  "Basic contact manager application",
  "Simple countdown timer tool",
  "Basic image gallery website",
  "Simple budget tracker tool",
  "Basic address book application",
  "Simple quiz application",
  "Basic recipe manager website",
  "Simple password manager tool",
  "Basic blog with search functionality",
  "Simple calendar tool",
  "Basic journaling application",
  "Simple countdown timer application",
  "Basic memo application",
  "Simple habit tracker tool",
  "Basic blog with categories feature",
  "Simple weight tracker tool",
  "Basic expense tracker tool",
  "Simple blog with pagination feature",
  "Basic reminder application",
  "Simple timer tool",
  "Basic blog with RSS feed",
  "Simple goal tracker tool",
  "Basic task scheduler application",
  "Simple note-taking tool",
  "Basic blog with comments feature",
  "Simple event reminder application",
  "Basic blog with archive feature",
  "Simple bookmark manager tool",
  "Basic blog with image upload feature",
  "Simple countdown application",
  "Basic blog with user authentication",
  "Simple password generator tool",
  "Basic blog with admin panel",
  "Simple blog with like button feature",
  "Basic blog with social sharing buttons",
  "Simple blog with tagging and filtering feature"
];

const intermediateList = [
    "Task management application with user authentication",
    "Blog platform with user profiles and commenting system",
    "E-commerce website with product search and filtering options",
    "Social media platform with user feeds and messaging functionality",
    "Online learning platform with course creation and enrollment features",
    "Real-time chat application with multiple chat rooms",
    "Recipe sharing platform with user-uploaded images and ratings",
    "Job board platform with job listings and application management",
    "Event management system with event creation and RSVP functionality",
    "Project management tool with task assignment and progress tracking",
    "Customer feedback portal with feedback submission and analysis",
    "Weather forecast website with customizable locations and alerts",
    "Stock trading simulator with real-time market data",
    "Appointment scheduling system with calendar integration",
    "Travel planning website with itinerary creation and booking options",
    "Music streaming service with playlist creation and recommendation engine",
    "Online survey creator with customizable survey templates",
    "Personal finance tracker with budgeting and expense categorization",
    "Healthcare appointment booking system with doctor profiles and availability",
    "Language learning platform with interactive lessons and quizzes",
    "Freelancer hiring platform with project posting and bidding system",
    "Virtual event platform with live streaming and audience interaction features",
    "Document sharing and collaboration tool with version control",
    "Online multiplayer game platform with matchmaking and leaderboards",
    "Property rental platform with property listings and booking management",
    "Online invoicing system with invoice creation and payment tracking",
    "Fitness tracker website with workout logging and progress visualization",
    "Car rental booking website with vehicle selection and reservation",
    "Crowdfunding platform with project funding and reward fulfillment",
    "Online therapy platform with therapist profiles and appointment scheduling",
    "Art portfolio marketplace with artist profiles and artwork listings",
    "Language exchange platform with language pairing and messaging",
    "Virtual fashion styling tool with virtual try-on and outfit creation",
    "Music collaboration platform with project collaboration and file sharing",
    "Digital art marketplace with artist storefronts and artwork sales",
    "Virtual roommate finder with matching algorithm and messaging system",
    "Local hiking trails directory with trail maps and difficulty ratings",
    "Online dating platform with user profiles and matching algorithms",
    "Virtual language immersion experience with interactive lessons and quizzes",
    "Personalized fitness coaching platform with tailored workout plans",
    "Tutoring marketplace with tutor profiles and lesson scheduling",
    "Home cleaning service booking website with service selection and scheduling",
    "Online therapy support group with moderated discussions and resources",
    "Virtual event networking platform with attendee profiles and messaging",
    "Pet adoption platform with pet profiles and adoption application process",
    "Remote team building activities platform with customizable activities",
    "Community gardening coordination tool with plot assignment and event scheduling",
    "Music playlist sharing platform with collaborative playlist creation",
    "Carpooling coordination tool with ride sharing and route planning",
    "Homework help forum with subject-specific discussion boards",
    "Wine pairing recommendation website with wine database and food pairing suggestions",
    "Online auction website with bidding functionality and auction item listings",
    "Personalized gift recommendation service with gift preferences and occasions",
    "Local farmers' market directory with vendor listings and product availability",
    "Virtual cooking classes platform with live streaming and recipe sharing",
    "Gourmet recipe sharing platform with chef profiles and video tutorials",
    "DIY craft project sharing platform with project instructions and materials lists",
    "Sports league management system with team management and scheduling",
    "Pantry inventory manager with barcode scanning and expiration date tracking",
    "Sustainable living tips and resources platform with articles and community forums",
    "Pet health tracker and reminder system with vaccination schedules and reminders",
    "Houseplant care advice and tracker with plant care tips and watering reminders",
    "Dog walking service booking platform with walker profiles and scheduling options",
    "Online dating profile optimization service with profile analysis and improvement tips",
    "Online multiplayer game platform with game lobbies and matchmaking",
    "Volunteer matching platform with volunteer opportunities and organization profiles",
    "Online auction website with bidding functionality and auction item listings",
    "Freelancer collaboration platform with project management and file sharing",
    "Local farmers' market directory with vendor listings and product availability",
    "Virtual cooking classes platform with live streaming and recipe sharing",
    "Gourmet recipe sharing platform with chef profiles and video tutorials",
    "DIY craft project sharing platform with project instructions and materials lists",
    "Sports league management system with team management and scheduling",
    "Pantry inventory manager with barcode scanning and expiration date tracking",
    "Sustainable living tips and resources platform with articles and community forums",
    "Pet health tracker and reminder system with vaccination schedules and reminders",
    "Houseplant care advice and tracker with plant care tips and watering reminders",
    "Dog walking service booking platform with walker profiles and scheduling options",
    "Online dating profile optimization service with profile analysis and improvement tips",
    "Online multiplayer game platform with game lobbies and matchmaking",
    "Volunteer matching platform with volunteer opportunities and organization profiles"
];

const hardList = [
    "Enterprise-level content management system (CMS) with user roles and permissions",
    "Social networking platform with real-time updates and notifications",
    "E-commerce marketplace with multiple sellers and advanced search features",
    "Online banking system with transaction history and account management",
    "Custom customer relationship management (CRM) system for businesses",
    "Healthcare management platform with electronic medical records (EMR) integration",
    "Online booking and reservation system for hotels or airlines",
    "Supply chain management system with inventory tracking and order processing",
    "Machine learning-powered recommendation engine for product/service recommendations",
    "Blockchain-based cryptocurrency exchange platform with secure transactions",
    "Real-time multiplayer gaming platform with game state synchronization",
    "Customizable e-learning platform with interactive lessons and assessments",
    "Integrated marketing automation platform for email campaigns and lead management",
    "Predictive analytics dashboard for business intelligence and data visualization",
    "Computer-aided design (CAD) software as a web application",
    "Cloud-based video editing suite with collaborative editing features",
    "Augmented reality (AR) or virtual reality (VR) immersive experience platform",
    "Internet of Things (IoT) dashboard for monitoring and controlling connected devices",
    "Custom search engine with web crawling and indexing capabilities",
    "Automated trading platform for stocks, cryptocurrencies, or commodities",
    "Custom digital asset management (DAM) system for media organizations",
    "Event ticketing and management platform with seating chart customization",
    "Remote desktop access and control application for technical support",
    "Custom customer support ticketing system with automated routing and escalation",
    "Advanced data visualization platform with interactive charts and dashboards",
    "Multi-factor authentication (MFA) system for securing user accounts",
    "Machine learning-powered chatbot for natural language processing",
    "Secure file storage and sharing platform with end-to-end encryption",
    "Virtual reality (VR) training simulator for industrial or educational purposes",
    "Custom online marketplace for freelancers and clients with escrow services",
    "Integrated smart home control system for managing IoT devices",
    "Real-time collaborative code editor for remote software development teams",
    "Blockchain-based digital identity verification platform",
    "Custom enterprise resource planning (ERP) system for business process management",
    "Automated voice transcription and translation service",
    "Custom search and rescue coordination platform for emergency services",
    "Secure document signing and verification platform using blockchain technology",
    "Automated drone fleet management system for aerial surveillance or delivery",
    "Custom artificial intelligence (AI) assistant for task automation and scheduling",
    "Automated sentiment analysis tool for social media monitoring",
    "Custom digital rights management (DRM) system for protecting intellectual property",
    "Advanced cybersecurity training platform with simulated cyber attacks",
    "Custom peer-to-peer (P2P) lending platform for decentralized finance (DeFi)",
    "Customized online medical diagnosis and treatment recommendation system",
    "Advanced natural language processing (NLP) platform for text analysis",
    "Custom predictive maintenance system for industrial equipment",
    "Blockchain-based supply chain traceability platform for product authenticity",
    "Integrated smart city management platform for urban infrastructure",
    "Advanced sentiment analysis tool for market research and consumer insights",
    "Custom recommendation engine for personalized content delivery",
    "Automated fraud detection and prevention system for financial transactions",
    "Integrated telemedicine platform for remote healthcare consultations",
    "Custom subscription-based content monetization platform for creators",
    "Advanced emotion recognition system for video content analysis",
    "Automated traffic management system for urban and highway networks",
    "Integrated smart energy management system for optimizing energy usage",
    "Custom inventory optimization and demand forecasting system",
    "Advanced geospatial data analysis platform for urban planning",
    "Automated social media content creation and scheduling tool",
    "Integrated biometric authentication system for identity verification",
    "Custom digital marketing analytics platform for campaign optimization",
    "Advanced recommendation engine for personalized health and wellness plans",
    "Integrated agricultural monitoring and management system for precision farming",
    "Custom automated trading algorithm for financial markets",
    "Advanced voice recognition system for voice-controlled applications",
    "Integrated disaster response and recovery coordination platform",
    "Custom autonomous vehicle fleet management system for transportation",
    "Advanced speech synthesis system for generating lifelike voices",
    "Custom predictive modeling platform for risk assessment and decision-making",
    "Integrated drone swarm coordination system for aerial displays or logistics",
    "Advanced facial recognition system for security and identity verification",
    "Custom self-driving car simulation environment for autonomous vehicle testing",
    "Integrated satellite imagery analysis platform for environmental monitoring",
    "Advanced augmented reality (AR) navigation system for indoor and outdoor use",
    "Custom recommendation engine for personalized financial advice",
    "Integrated smart building management system for energy efficiency",
    "Advanced natural disaster prediction and early warning system",
    "Custom virtual reality (VR) training platform for medical professionals",
    "Integrated asset tracking and management system for logistics and supply chain",
    "Advanced emotion-aware user interface for personalized user experiences",
    "Custom fraud detection system for financial institutions",
    "Integrated smart grid management platform for optimizing energy distribution",
    "Advanced computer vision system for object recognition and classification",
    "Custom adaptive learning platform for personalized education",
    "Integrated predictive maintenance system for industrial machinery",
    "Advanced medical image analysis platform for diagnosis and treatment planning",
    "Custom automated stock trading algorithm for algorithmic trading strategies",
    "Integrated smart transportation management system for traffic optimization",
    "Advanced recommendation engine for personalized travel itineraries"
];

const extremeList = [
    "Building a web-based operating system",
    "Creating a distributed computing platform for scientific research",
    "Developing a secure cryptocurrency exchange platform",
    "Building a large-scale real-time analytics dashboard for IoT data",
    "Implementing a decentralized autonomous organization (DAO) platform",
    "Developing a high-frequency trading platform for financial markets",
    "Building a sophisticated recommendation engine for personalized content delivery",
    "Creating a scalable cloud-based gaming platform with real-time multiplayer capabilities",
    "Implementing a self-learning chatbot with natural language processing (NLP)",
    "Developing a comprehensive enterprise resource planning (ERP) system for businesses",
    "Building a complex automated trading system for stock markets",
    "Creating a cloud-based healthcare management system with electronic health records (EHR)",
    "Developing a cutting-edge machine learning platform for predictive analytics",
    "Building a blockchain-based digital identity management system",
    "Implementing a high-performance, fault-tolerant distributed database system",
    "Creating a virtual reality (VR) simulation platform for training and education",
    "Developing a quantum computing simulation platform for research purposes",
    "Building a real-time bidding platform for online advertising",
    "Implementing a federated learning framework for privacy-preserving machine learning",
    "Developing a large-scale recommendation system for personalized shopping experiences",
    "Creating a decentralized marketplace for digital assets",
    "Building an AI-powered automated trading system for cryptocurrencies",
    "Developing a platform for secure and anonymous communication",
    "Creating a distributed social network with blockchain-based identity verification",
    "Building a real-time fraud detection system for financial transactions",
    "Developing a high-throughput data processing platform for big data analytics",
    "Implementing a decentralized storage network for file sharing",
    "Building a platform for secure and private messaging",
    "Creating a decentralized content distribution network (CDN)",
    "Developing a blockchain-based voting system for elections",
    "Building an AI-powered virtual assistant for businesses",
    "Creating a decentralized autonomous ride-sharing platform",
    "Developing a blockchain-based supply chain management system",
    "Building a distributed ledger for tracking intellectual property rights",
    "Creating a decentralized marketplace for digital art and collectibles",
    "Developing a platform for decentralized prediction markets",
    "Building an AI-driven automated customer support system",
    "Creating a decentralized finance (DeFi) platform for lending and borrowing",
    "Developing a blockchain-based identity verification system for KYC/AML compliance",
    "Building a platform for decentralized governance and decision-making",
    "Creating a distributed storage platform for archival and backup purposes",
    "Developing an AI-powered virtual fashion designer",
    "Building a decentralized peer-to-peer energy trading platform",
    "Creating a platform for decentralized domain name registration and hosting",
    "Developing a blockchain-based digital rights management (DRM) system",
    "Building an AI-powered medical diagnosis and treatment recommendation system",
    "Creating a decentralized marketplace for freelancers and gig workers",
    "Developing a blockchain-based platform for tokenized real estate investments",
    "Building a distributed computing platform for scientific simulations",
    "Creating a decentralized exchange (DEX) for trading digital assets",
    "Developing an AI-powered automated content creation system",
    "Building a platform for decentralized lending and borrowing",
    "Creating a distributed reputation system for online communities",
    "Developing a blockchain-based platform for crowdfunding and fundraising",
    "Building an AI-driven automated investment advisor",
    "Creating a decentralized storage and computation platform for AI applications",
    "Developing a blockchain-based platform for decentralized governance",
    "Building a distributed marketplace for peer-to-peer insurance",
    "Creating a platform for decentralized identity management and authentication",
    "Developing an AI-powered virtual travel advisor",
    "Building a decentralized marketplace for healthcare services",
    "Creating a distributed platform for secure and verifiable electronic voting",
    "Developing a blockchain-based platform for decentralized finance (DeFi) derivatives",
    "Building a platform for decentralized social media monetization",
    "Creating a distributed reputation system for e-commerce platforms",
    "Developing an AI-powered virtual personal shopper",
    "Building a decentralized marketplace for renewable energy trading",
    "Creating a platform for decentralized content monetization and distribution",
    "Developing a blockchain-based platform for decentralized insurance",
    "Building a distributed platform for secure and private messaging",
    "Creating a decentralized marketplace for tokenized digital assets",
    "Developing an AI-driven personalized medicine platform",
    "Building a platform for decentralized crowdfunding of scientific research",
    "Creating a distributed platform for secure and anonymous communication",
    "Developing a blockchain-based platform for decentralized social networking",
    "Building an AI-powered automated legal advisor",
    "Creating a decentralized marketplace for intellectual property rights",
    "Developing a distributed platform for secure and private file sharing",
    "Building a platform for decentralized identity verification and authentication",
    "Creating a distributed reputation system for online marketplaces",
    "Developing an AI-driven virtual personal assistant for healthcare",
    "Building a decentralized platform for tokenized real estate crowdfunding",
    "Creating a platform for decentralized governance of digital communities",
    "Developing a blockchain-based platform for decentralized prediction markets"
];

const arrayList = [easyList, intermediateList, hardList, extremeList];

let selectedIdea;
let selectedDifficulty;
let difficultyName;

// Select an Difficulty level
function selectDifficulty() {

  if(easyRadio.checked) {
    selectedDifficulty = arrayList[0];
    difficultyName = "easy";
  }
  else if(intermediateRadio.checked) {
    selectedDifficulty = arrayList[1];
    difficultyName = "intermediate";
  }
  else if(hardRadio.checked) {
    selectedDifficulty = arrayList[2];
    difficultyName = "hard";
  }
  else if(extremeRadio.checked) {
    selectedDifficulty = arrayList[3];
    difficultyName = "extreme";
  }
}

// Select a single idea suggestion from the chosen difficulty level

function selectIdea() {

  let randomIndex = Math.floor(Math.random() * selectedDifficulty.length);
  console.log(randomIndex);
  selectedIdea = selectedDifficulty[ randomIndex];
  console.log(difficultyName)
  console.log(selectedIdea);
}

//Display selected idea suggestion

function displayIdea() {
  display.innerText =  selectedIdea;
}

//Prevent page reload on submit/random button click
form.addEventListener("submit", function(event) {

  selectDifficulty();

  selectIdea();

  displayIdea();

  event.preventDefault();
});